# Change to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'https-yu-an-github-io'

#google-ID: 'UA-112060364-1'

menu:
- {name: 'My Name', path: 'menu', url: 'about.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Publication', path: 'menu', url: 'publication.html'}
- {name: 'Teaching', path: 'menu', url: 'teaching.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'CV', path: 'menu', url: 'cv.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/yu-an'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
